apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-ce60"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-ce60"
  template:
    metadata:
      labels:
        app: "myaks-ce60"
    spec:
      containers:
        - name: "myaks-ce60"
          image: "himanshucontainerregistry.azurecr.io/myaks"
          ports:
          - containerPort: 80